### ISSUE TITLE
Sprint 1 Project Feedback

### ISSUE THREAD

**Issue by greyatom-school** [pranay407/ark-studio#1]
|     | Hits                                           | Misses                                            |   Additional Comments |   Final Score(Out of 5) |
|----:|:-----------------------------------------------|:--------------------------------------------------|----------------------:|------------------------:|
| nan | "- The page has all The required elements      | - HTML formatting rules are not followed properly |                   nan |                    3.75 |
|     |  - HTML formatting rules are followed properly |  - The page doesn't follow good UI/UX structure   |                       |                         |
|     |  - CSS formatting rules are followed properly" |                                                   |                       |                         |

**Comment by pranay407** [comment]
I made changes in css file of the page i.e main.css
And try to restructure the page as per requirements you can see changes in main css file
